INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "ACURA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "AUDI", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "BMW", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "BOBCAT", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "CADILLAC", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "CATERPILLAR", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "CHEVROLET", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "CHRYSLER", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "DAF", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "DINA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "DODGE", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "FIAT", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "FORD", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "FREIGHTLINER", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "FRUEHAUF", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "GMC", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "HITACHI", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "HONDA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "HUMMER", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "HYUNDAI", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "INTERNATIONAL", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "ISUZU", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "JAGUAR", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "JEEP", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "JOHN DEERE", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "KENWORTH", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "LAND ROVER", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "LINCOLN", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "MAN", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "MAZDA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "MERCEDEZ BENZ", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "MINI", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "MITSUBISHI", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "NEW HOLLAND", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "NISSAN", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "OPEL", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "PEUGEOT", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "PONTIAC", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "RENAULT", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "SEAT", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "SIN MARCA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "SUBARU", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "SUZUKI", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "TOYOTA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "TOYOTA", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "VOLKSWAGEN", TRUE);
INSERT INTO marca_unidad(id_marca, nombre, status) VALUES(NULL, "VOLVO", TRUE);
