/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package almacendgv;

import beans.SistemaDTO;
import bussines.SistemaBO;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import logger.ErrorLogger;
import mailer.MailData;

/**
 *
 * @author David Israel
 */
public class ControlSistema extends javax.swing.JFrame {

    /**
     * Creates new form ControlSistema
     */
    public ControlSistema() {
        try{
            initComponents();
            this.cargarConfiguraciones();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Código error: 1371\n" + ex.getMessage(),
                    "Error!!!", JOptionPane.ERROR_MESSAGE); 
            ErrorLogger.scribirLog("ControlSistema Constructor()", 1371, UserHome.getUsuario(), ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLLogo = new javax.swing.JLabel();
        jPOrdenesReparacion = new javax.swing.JPanel();
        jCBNotificarAperturas = new javax.swing.JCheckBox();
        jCBNotificarCierres = new javax.swing.JCheckBox();
        jBVerListaCorreosReparaciones = new javax.swing.JButton();
        jPControlExcepciones = new javax.swing.JPanel();
        jCBNotificarExcepcionesCorreo = new javax.swing.JCheckBox();
        jBVerListaCorreosExcepciones = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();
        jMBMenu = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMIGuardar = new javax.swing.JMenuItem();
        jMISalir = new javax.swing.JMenuItem();
        jMAyuda = new javax.swing.JMenu();
        jMIVerManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración del Sistema");
        setResizable(false);

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Efectivo Negro Chico.png"))); // NOI18N

        jPOrdenesReparacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Órdenes de Reparación"));

        jCBNotificarAperturas.setText("Notificar aperturas por correo");

        jCBNotificarCierres.setText("Notificar cierres por correo");

        jBVerListaCorreosReparaciones.setText("Ver lista de correos");
        jBVerListaCorreosReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerListaCorreosReparacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOrdenesReparacionLayout = new javax.swing.GroupLayout(jPOrdenesReparacion);
        jPOrdenesReparacion.setLayout(jPOrdenesReparacionLayout);
        jPOrdenesReparacionLayout.setHorizontalGroup(
            jPOrdenesReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOrdenesReparacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOrdenesReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBNotificarAperturas)
                    .addComponent(jCBNotificarCierres))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOrdenesReparacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVerListaCorreosReparaciones)
                .addContainerGap())
        );
        jPOrdenesReparacionLayout.setVerticalGroup(
            jPOrdenesReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOrdenesReparacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBNotificarAperturas)
                .addGap(18, 18, 18)
                .addComponent(jCBNotificarCierres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jBVerListaCorreosReparaciones)
                .addContainerGap())
        );

        jPControlExcepciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Control de Excepciones"));

        jCBNotificarExcepcionesCorreo.setText("Notificar excepciones por correo");

        jBVerListaCorreosExcepciones.setText("Ver lista de correos");
        jBVerListaCorreosExcepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerListaCorreosExcepcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPControlExcepcionesLayout = new javax.swing.GroupLayout(jPControlExcepciones);
        jPControlExcepciones.setLayout(jPControlExcepcionesLayout);
        jPControlExcepcionesLayout.setHorizontalGroup(
            jPControlExcepcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPControlExcepcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBNotificarExcepcionesCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVerListaCorreosExcepciones)
                .addContainerGap())
        );
        jPControlExcepcionesLayout.setVerticalGroup(
            jPControlExcepcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPControlExcepcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPControlExcepcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBNotificarExcepcionesCorreo)
                    .addComponent(jBVerListaCorreosExcepciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jMArchivo.setText("Archivo");

        jMIGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMIGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Apply-16.png"))); // NOI18N
        jMIGuardar.setText("Guardar");
        jMIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGuardarActionPerformed(evt);
            }
        });
        jMArchivo.add(jMIGuardar);

        jMISalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMISalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit-16.png"))); // NOI18N
        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMArchivo.add(jMISalir);

        jMBMenu.add(jMArchivo);

        jMAyuda.setText("Ayuda");

        jMIVerManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMIVerManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help-16.png"))); // NOI18N
        jMIVerManual.setText("Ver manual");
        jMIVerManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVerManualActionPerformed(evt);
            }
        });
        jMAyuda.add(jMIVerManual);

        jMBMenu.add(jMAyuda);

        setJMenuBar(jMBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPOrdenesReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLLogo))
                    .addComponent(jPControlExcepciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBAceptar, jBCancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLogo)
                    .addComponent(jPOrdenesReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPControlExcepciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGuardarActionPerformed
        this.guardar();
    }//GEN-LAST:event_jMIGuardarActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        this.cancelar();
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMIVerManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVerManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIVerManualActionPerformed

    private void jBVerListaCorreosReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerListaCorreosReparacionesActionPerformed
        verListaCorreosMailer();
    }//GEN-LAST:event_jBVerListaCorreosReparacionesActionPerformed

    private void jBVerListaCorreosExcepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerListaCorreosExcepcionesActionPerformed
        verListaCorreosExcepciones();
    }//GEN-LAST:event_jBVerListaCorreosExcepcionesActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        this.guardar();
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.cancelar();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void verListaCorreosExcepciones(){
        try {
            File file = new File(new MailData().getPathSoporte());
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Código error: 1372\n" + ex.getMessage(),
                    "Error!!!", JOptionPane.ERROR_MESSAGE); 
            ErrorLogger.scribirLog("ControlSistema verListaCorreosExcepciones()", 1372, UserHome.getUsuario(), ex);
        }
    }
    
    private void verListaCorreosMailer(){
        try {
            File file = new File(new MailData().getPathMailer());
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Código error: 1373\n" + ex.getMessage(),
                    "Error!!!", JOptionPane.ERROR_MESSAGE); 
            ErrorLogger.scribirLog("ControlSistema verListaCorreosMailer()", 1373, UserHome.getUsuario(), ex);
        }
    }
    
    private void guardar(){
        try{
            SistemaDTO sistema = new SistemaDTO();
            SistemaBO accesoSistema = new SistemaBO();
            boolean notificarFinalizacionOrden = jCBNotificarCierres.isSelected();
            boolean notificarAperturaOrden = jCBNotificarAperturas.isSelected();
            boolean notificarExcepciones = jCBNotificarExcepcionesCorreo.isSelected();
            sistema.setIdSistema(1);
            sistema.setNotificarFinOrden(notificarFinalizacionOrden);
            sistema.setNotificarNuevaOrden(notificarAperturaOrden);

            accesoSistema.modificarControlSistema(sistema);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Código error: 1374\n" + ex.getMessage(),
                    "Error!!!", JOptionPane.ERROR_MESSAGE); 
            ErrorLogger.scribirLog("ControlSistema guardar()", 1374, UserHome.getUsuario(), ex);
        }
        dispose();
    }
    
    private void cancelar(){
        this.dispose();
    }
    
    private void cargarConfiguraciones(){
        try{
            SistemaDTO sistema = new SistemaBO().obtenerControlSistema(1, true, true);

            this.jCBNotificarAperturas.setSelected(sistema.isNotificarNuevaOrden());
            this.jCBNotificarCierres.setSelected(sistema.isNotificarFinOrden());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Código error: 1375\n" + ex.getMessage(),
                    "Error!!!", JOptionPane.ERROR_MESSAGE); 
            ErrorLogger.scribirLog("ControlSistema cargarConfiguraciones()", 1375, UserHome.getUsuario(), ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBVerListaCorreosExcepciones;
    private javax.swing.JButton jBVerListaCorreosReparaciones;
    private javax.swing.JCheckBox jCBNotificarAperturas;
    private javax.swing.JCheckBox jCBNotificarCierres;
    private javax.swing.JCheckBox jCBNotificarExcepcionesCorreo;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenu jMAyuda;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenuItem jMIVerManual;
    private javax.swing.JPanel jPControlExcepciones;
    private javax.swing.JPanel jPOrdenesReparacion;
    // End of variables declaration//GEN-END:variables
}
