/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package almacendgv;

import beans.LogInDTO;
import beans.UsuarioDTO;
import bussines.LogInBO;
import data.UsuarioDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logger.ErrorLogger;

/**
 *
 * @author David Israel
 */
public class Logging extends javax.swing.JFrame {

    /**
     * Creates new form Logging
     */
    public Logging() {
        try{
            initComponents();
            this.setLocationRelativeTo(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Código error: 1062\n" + ex.getMessage(),
                    "Error al iniciar ventana de Logging!!!", JOptionPane.ERROR_MESSAGE);
            ErrorLogger.scribirLog("Constructor Logging()", 1062, UserHome.getUsuario(), ex);
            this.dispose();
        }
    }
    
    /**
     * Change the default icon image in the JFrame.
     * 
     * @return an icon for the JFrame.
     */
    @Override
    public Image getIconImage() {
        try{
            Image retValue = Toolkit.getDefaultToolkit().
                    getImage(ClassLoader.getSystemResource("icons/3D-Key-Logging.png"));
            return retValue;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Código error: 1063\n"
                        + "No se pudo obtener el icono de la aplicación.", "Error!!!",
                        JOptionPane.ERROR_MESSAGE);
            ErrorLogger.scribirLog("Logging getIconImage()", 1063, UserHome.getUsuario(), ex);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitle = new javax.swing.JLabel();
        jLEmployeeID = new javax.swing.JLabel();
        jTFEmployeeID = new javax.swing.JTextField();
        jLEmployeePassword = new javax.swing.JLabel();
        jBLogIn = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jPFEmployeePassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setIconImage(getIconImage());
        setResizable(false);

        jLTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTitle.setText("Inicio de Sesión");

        jLEmployeeID.setText("Nombre Empleado:");

        jTFEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmployeeIDActionPerformed(evt);
            }
        });

        jLEmployeePassword.setText("Password:");

        jBLogIn.setText("Ingresar");
        jBLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogInActionPerformed(evt);
            }
        });

        jBExit.setText("Salir");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        jPFEmployeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFEmployeePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBLogIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBExit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEmployeePassword)
                            .addComponent(jLEmployeeID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEmployeeID)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTitle)
                                .addGap(0, 104, Short.MAX_VALUE))
                            .addComponent(jPFEmployeePassword))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBExit, jBLogIn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmployeeID)
                    .addComponent(jTFEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmployeePassword)
                    .addComponent(jPFEmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLogIn)
                    .addComponent(jBExit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogInActionPerformed
        this.login();
    }//GEN-LAST:event_jBLogInActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBExitActionPerformed

    private void jPFEmployeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFEmployeePasswordActionPerformed
        this.login();
    }//GEN-LAST:event_jPFEmployeePasswordActionPerformed

    private void jTFEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmployeeIDActionPerformed
        this.login();
    }//GEN-LAST:event_jTFEmployeeIDActionPerformed

    private void login(){
        LogInDTO log = new LogInDTO(this.jTFEmployeeID.getText(), 
                new String(this.jPFEmployeePassword.getPassword()));
        int n = new LogInBO().esValido(log);
        if(n == 0){
            JOptionPane.showMessageDialog(null, "Datos Incorrectos", 
                    "Error inicio de sesion", JOptionPane.ERROR_MESSAGE);
        } else {
            UsuarioDTO usuario = null;
            try {
                usuario = new UsuarioDAO().obtenerUsuario(n, true, true);
                UserHome.setUsuario(usuario);
                UserHome home = new UserHome();
                home.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Logging.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Código error: 1064\n"
                        + "Error al accesar a la información\n de inicio de sesión.", "Error!!!",
                        JOptionPane.ERROR_MESSAGE);
                ErrorLogger.scribirLog(usuario.toString(), 1064, usuario, ex);
            } catch (Exception ex) {
                Logger.getLogger(Logging.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Código error: 1065\n"
                        + "Error al iniciar sesión.", "Error!!!",
                        JOptionPane.ERROR_MESSAGE);
                ErrorLogger.scribirLog(usuario.toString(), 1065, usuario, ex);
            }
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logging().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBLogIn;
    private javax.swing.JLabel jLEmployeeID;
    private javax.swing.JLabel jLEmployeePassword;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPasswordField jPFEmployeePassword;
    private javax.swing.JTextField jTFEmployeeID;
    // End of variables declaration//GEN-END:variables
}
